# fly.toml app configuration file generated for my-mysql-patient-forest-6347 on 2024-12-09T14:40:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mysql-patient-forest-6347'
primary_region = 'bog'

[build]
  image = 'mysql:8.4'

[env]
  MYSQL_DATABASE = 'campuscal'
  MYSQL_USER = 'campuscal'

[processes]
  app = '--datadir /data/mysql --mysql-native-password=ON'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
